///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CatEntity {
/*
{
  "id": "a5k",
  "url": "https://25.media.tumblr.com/tumblr_m3by679GYk1qze0hyo1_250.jpg",
  "width": 240,
  "height": 240
} 
*/

  String? id;
  String? url;
  int? width;
  int? height;

  CatEntity({
    this.id,
    this.url,
    this.width,
    this.height,
  });
  CatEntity.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    url = json['url']?.toString();
    width = json['width']?.toInt();
    height = json['height']?.toInt();
  }
}
